# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyruin < Formula
  desc "TUI for the ruin note-taking CLI"
  homepage "https://github.com/donnellyk/lazyruin"
  version "0.2.0"
  license "MIT"

  depends_on "ruin-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.2.0/lazyruin-darwin-amd64.tar.gz"
      sha256 "3a1be12de357628a560503bafc441c8ed3eefe76ceb26738554bea3224fc4928"

      define_method(:install) do
        bin.install "lazyruin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.2.0/lazyruin-darwin-arm64.tar.gz"
      sha256 "4bfa6db15ff15e084281d41c8eb223a36b35b69ee7fe4dde34190a9e1f51d185"

      define_method(:install) do
        bin.install "lazyruin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.2.0/lazyruin-linux-amd64.tar.gz"
      sha256 "379b1983114858bfbdc4a279388969727f5f6d207696e94c87087e9697a0b1db"
      define_method(:install) do
        bin.install "lazyruin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.2.0/lazyruin-linux-arm64.tar.gz"
      sha256 "c94550dc399c9186abda31a2c289b41d2c4903e5693bc72bde8620dddfc1b945"
      define_method(:install) do
        bin.install "lazyruin"
      end
    end
  end
end
