# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyruin < Formula
  desc "TUI for the ruin note-taking CLI"
  homepage "https://github.com/donnellyk/lazyruin"
  version "0.3.0"
  license "MIT"

  depends_on "ruin-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.3.0/lazyruin-darwin-amd64.tar.gz"
      sha256 "7e0b193ca62b2b8bad2254aab95b3f1e19d92018a79bdc064a037c439049e9c8"

      define_method(:install) do
        bin.install "lazyruin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.3.0/lazyruin-darwin-arm64.tar.gz"
      sha256 "07809d497e077163cb6e8e9e2bb055180c77618c1e1cc313a48d9d864162cfb5"

      define_method(:install) do
        bin.install "lazyruin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.3.0/lazyruin-linux-amd64.tar.gz"
      sha256 "0f0654501ca9fd1b92dd989b04ba9f27ec7fe08ce4fab9aff533ba9348ea359e"
      define_method(:install) do
        bin.install "lazyruin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.3.0/lazyruin-linux-arm64.tar.gz"
      sha256 "b8d327b791dabb6843c8606f2cdc86b8af16f16dfc337c8eaceff6436e455e75"
      define_method(:install) do
        bin.install "lazyruin"
      end
    end
  end
end
