# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyruin < Formula
  desc "TUI for the ruin note-taking CLI"
  homepage "https://github.com/donnellyk/lazyruin"
  version "0.1.0"
  license "MIT"

  depends_on "ruin-cli"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.1.0/lazyruin-darwin-amd64.tar.gz"
      sha256 "a30edef8e9e30d9baaf113f7aacf671df7105e4c9427f819aa1ebabffdc09369"

      define_method(:install) do
        bin.install "lazyruin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.1.0/lazyruin-darwin-arm64.tar.gz"
      sha256 "65bb73bab65498badb75a86b2f1ee6078014a7040e3550c3709d0487cbe4e33e"

      define_method(:install) do
        bin.install "lazyruin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.1.0/lazyruin-linux-amd64.tar.gz"
      sha256 "20ff2a2c21f8f958d0ebe0f9eb843bf21fc4b977242dbdc50f4d754659877007"
      define_method(:install) do
        bin.install "lazyruin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/lazyruin/releases/download/v0.1.0/lazyruin-linux-arm64.tar.gz"
      sha256 "846dfe2e520e98a89c1a55bb2fff18a659d1213d0438890ab2486e2b1211bbe5"
      define_method(:install) do
        bin.install "lazyruin"
      end
    end
  end
end
