# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RuinCli < Formula
  desc "A Zettelkasten-inspired note-taking CLI"
  homepage "https://github.com/donnellyk/ruin-note-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/donnellyk/ruin-note-cli/releases/download/v0.2.0/ruin-darwin-amd64.tar.gz"
      sha256 "c5be36d68a4f3ed0c92b158501e4c5c94bcb63c9473b26ad36a6eb8fb14bba8b"

      define_method(:install) do
        bin.install "ruin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/donnellyk/ruin-note-cli/releases/download/v0.2.0/ruin-darwin-arm64.tar.gz"
      sha256 "7c2bdd9900dc19901053f1e10c92161de5cef3c91ce61ea45588ea20b710a238"

      define_method(:install) do
        bin.install "ruin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/ruin-note-cli/releases/download/v0.2.0/ruin-linux-amd64.tar.gz"
      sha256 "fb2665dcdb56315455fbc02ddaab40b2e1c96571fbda2d1327101e3ebb035fbe"
      define_method(:install) do
        bin.install "ruin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/donnellyk/ruin-note-cli/releases/download/v0.2.0/ruin-linux-arm64.tar.gz"
      sha256 "124999e536217c9b47883c9728ea940cc880bed1ddf13a39d36832fb9f58b56d"
      define_method(:install) do
        bin.install "ruin"
      end
    end
  end
end
